// The Chrome offline dinosaur, but a triceratops. Faye drew this one; it lives
// here as a character grid rather than as a PNG so it can be diffed and nudged a
// pixel at a time, which is the only way a silhouette this small stays readable.
//
// '#' is solid, '.' is transparent, 'o' is a hole punched through the solid (the
// eye). Facing right, so it walks the way text reads.
//
// Recovered from her drawing with scripts/import-trike.mjs — see that file for
// how the original resolution was found. Two cells are hand-corrections the
// importer could not make on its own: the belly cell that reattaches the front
// leg, which the source joins across less than one pixel, and the eye, which she
// drew a shade off the grid so it quantised into a two-pixel slit.
export const TRIKE = `
.........................###.................
........................#####................
.......................#######.........#.....
........................#######.......##.....
.......................#########.....##....#.
.......................#########....##....##.
...............#####....##########.##....##..
.............##########.############....##...
...........############..###########..###....
..........##############.###############.....
.........###############..##############....#
........##################o######o#######..##
........###################o################.
.......######################################
......#######################################
.....########################################
...#####################################.####
..##############################..........##.
########..#####################..............
..........######################.............
..........####..###.....####.##..............
.........#####..###.....####.##..............
.........####...###....####..###.............
.........####...####...####..####............
.........#####..####...#####.####............
.........#####.........#####.................
`
  .trim()
  .split('\n')

export const TRIKE_INK = '#1c1b1a'
